name: Init Repo

on:
  push:
    branches: '**'
  workflow_dispatch:

env:
  APP: ${{ github.event.repository.name }}

jobs:
  init:
    if: github.event.repository.name != 'platform-microservice-template' && github.event.head_commit.message == 'Initial commit' 
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: update Chart
        run: |
          find . -type f ! -path "./.git/*" ! -path "./.github/*" ! -path "./node_modules/*" -print0 | xargs -0 sed -i "s/elementor-lerna-template/${APP}/g"
          
      - name: delete init workflow
        run: |
          git rm .github/workflows/initrepo.yaml

      - name: enable settings
        run: |
          git mv .github/settings.yml.disabled .github/settings.yml
          
      - name: Update Repo
        run: |
          git pull --rebase --autostash
          git -c "user.name=Bot" -c "user.email=bot@cloud-gitops" commit --allow-empty -am "Updating Files"
          git push

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: "1.0.0"
          name: "1.0.0: Initial Release"
          draft: false
          prerelease: false


          
