name: Publish

on:
  release:
    types: [published]

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  pre-job:
    uses: elementor/elementor-cloud-github-actions/.github/workflows/microservice-pre-job.yaml@master
    secrets: inherit

  affected-packages:
    uses: elementor/elementor-cloud-github-actions/.github/workflows/monorepo-affected-packages.yaml@master
    with:
      event: 'release'
      workflow_id: 'publish.yaml'
    secrets: inherit

  publish:
    needs: ["pre-job", "affected-packages"]
    name: Publish
    if: fromJson(needs.affected-packages.outputs.affected_projects).packages[0] != null
    strategy:
      matrix:
        lib: ${{ fromJson(needs.affected-packages.outputs.affected_projects).packages }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.CLOUD_DEVOPS_TOKEN }}

    - name: Install Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        registry-url: https://npm.pkg.github.com/@elementor
        cache: npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.CLOUD_DEVOPS_TOKEN }}

    - name: Install Deps
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.CLOUD_DEVOPS_TOKEN }}
        
    - name: Run Build
      run: npm run build

    - name: Publishing ${{ matrix.lib }}
      run: |
        PACKAGE=${{ matrix.lib }}
        export PACKAGE=${PACKAGE#@elementor}
        cd packages/${PACKAGE}/dist
        npm version ${{ needs.pre-job.outputs.VERSION }}
        npm publish         
      env:
        token: ${{ secrets.CLOUD_DEVOPS_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.CLOUD_DEVOPS_TOKEN }}
